-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 16:41:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_alugue_direto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_alugue_direto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_alugue_direto` DEFAULT CHARACTER SET utf8 ;
USE `db_alugue_direto` ;

-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb002_nivel_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb002_nivel_access` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb009_plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb009_plataforma` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `valor_plano` VARCHAR(45) NULL,
  `nome_plano` VARCHAR(45) NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb006_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb006_status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb001_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb001_usuario` (
  `id_dados` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `sobrenome` VARCHAR(120) NULL,
  `endereco` VARCHAR(120) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(100) NULL,
  `cep` VARCHAR(45) NULL,
  `telefone1` VARCHAR(45) NULL,
  `telefone2` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `data_create` VARCHAR(45) NULL,
  `data_update` VARCHAR(45) NULL,
  `id_plano` INT NOT NULL,
  `id_status` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  PRIMARY KEY (`id_dados`),
  INDEX `fk_tb003_dados_user_tb009_plataforma1_idx` (`id_plano` ASC),
  INDEX `fk_tb001_dados_user_tb006_status1_idx` (`id_status` ASC),
  INDEX `fk_tb001_dados_user_tb002_nivel_access1_idx` (`id_nivel` ASC),
  CONSTRAINT `fk_tb003_dados_user_tb009_plataforma1`
    FOREIGN KEY (`id_plano`)
    REFERENCES `db_alugue_direto`.`tb009_plataforma` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb001_dados_user_tb006_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `db_alugue_direto`.`tb006_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb001_dados_user_tb002_nivel_access1`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `db_alugue_direto`.`tb002_nivel_access` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb004_documentos_principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb004_documentos_principal` (
  `id_docs` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `identidade` VARCHAR(45) NOT NULL,
  `cpf_file` VARCHAR(45) NOT NULL,
  `identidade_file` VARCHAR(45) NOT NULL,
  `comprovante_file` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NULL,
  `cnpj_file` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_docs`),
  INDEX `fk_tb004_documentos_principal_tb001_dados_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb004_documentos_principal_tb001_dados_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_alugue_direto`.`tb001_usuario` (`id_dados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb005_documentos_fiador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb005_documentos_fiador` (
  `id_docs_fiador` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `identidade` VARCHAR(45) NULL,
  `nome` VARCHAR(220) NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone1` VARCHAR(45) NULL,
  `telefone2` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `atividade` VARCHAR(45) NULL,
  `cpf_file` VARCHAR(45) NULL,
  `comprovante_file` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `cnpj_file` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_docs_fiador`),
  INDEX `fk_tb005_documentos_fiador_tb001_usuario1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb005_documentos_fiador_tb001_usuario1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_alugue_direto`.`tb001_usuario` (`id_dados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb003_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb003_imovel` (
  `id_imovel` INT NOT NULL,
  `nome` VARCHAR(220) NULL,
  `descricao` VARCHAR(300) NULL,
  `tipo` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `quartos` VARCHAR(45) NULL,
  `garagem` VARCHAR(45) NULL,
  `andar` VARCHAR(45) NULL,
  `area_total` VARCHAR(45) NULL,
  `cozinha` VARCHAR(45) NULL,
  `varanda` VARCHAR(45) NULL,
  `metros_quadrados` VARCHAR(45) NULL,
  `banheiro` VARCHAR(45) NULL,
  `casal` VARCHAR(45) NULL,
  `habitantes` VARCHAR(45) NULL,
  `crianca` VARCHAR(45) NULL,
  `lazer` VARCHAR(45) NULL,
  `piscina` VARCHAR(45) NULL,
  `churrasqueira` VARCHAR(45) NULL,
  `fotos_casa` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_imovel`),
  INDEX `fk_tb011_imovel_tb003_dados_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb011_imovel_tb003_dados_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_alugue_direto`.`tb001_usuario` (`id_dados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb007_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb007_contrato` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `tempo_contrato` VARCHAR(45) NULL,
  `tipo_contrato` VARCHAR(45) NULL,
  `chekin` DATETIME NULL,
  `checkout` DATETIME NULL,
  `id_imovel` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_contrato`),
  INDEX `fk_tb007_contrato_tb011_imovel1_idx` (`id_imovel` ASC),
  INDEX `fk_tb007_contrato_tb001_dados_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb007_contrato_tb011_imovel1`
    FOREIGN KEY (`id_imovel`)
    REFERENCES `db_alugue_direto`.`tb003_imovel` (`id_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb007_contrato_tb001_dados_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_alugue_direto`.`tb001_usuario` (`id_dados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb008_pagamento_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb008_pagamento_imovel` (
  `id_pag_imovel` INT NOT NULL AUTO_INCREMENT,
  `foma_pagamento` VARCHAR(45) NULL,
  `parcelas` VARCHAR(45) NULL,
  `adiantamento` VARCHAR(45) NULL,
  `valor_final` VARCHAR(30) NULL,
  `Valor_mensal` VARCHAR(45) NULL,
  `valor_entrada` VARCHAR(45) NULL,
  `data_vencimento` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_pag_imovel`),
  INDEX `fk_tb008_pagamento_imovel_tb001_dados_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb008_pagamento_imovel_tb001_dados_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_alugue_direto`.`tb001_usuario` (`id_dados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_alugue_direto`.`tb010_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_alugue_direto`.`tb010_avaliacao` (
  `id_avaliacao` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `obs` VARCHAR(220) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `fk_tb010_avaliacao_tb001_dados_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb010_avaliacao_tb001_dados_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_alugue_direto`.`tb001_usuario` (`id_dados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
